name: Build and Test

on:
 push:
   branches:
     - 'master'
 pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: ["1.21.x", "1.22.x"]
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.version }}
          cache: true

      - name: generate and test
        run: go test -race -cover -coverprofile=coverage.out ./...

      - uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          files: ./coverage.out
